// SPDX-License-Identifier: MIT

#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

namespace fs = std::filesystem;

namespace
{

struct TemplateSpec
{
    std::string id;
    std::string description;
    std::string features;
    std::string mainSource;
};

TemplateSpec FindTemplate(const std::string& id)
{
    if (id == "2d")
    {
        return {"2d", "rbfx 2D game starter", "2D, Urho2D, Physics2D",
            R"cpp(#include <Urho3D/Engine/Engine.h>
#include <Urho3D/Urho2D/Sprite2D.h>

using namespace Urho3D;

class GameApplication : public Application
{
public:
    explicit GameApplication(Context* context) : Application(context) {}
    void Start() override
    {
        engine_->Create();
        // Create the 2D scene, camera and gameplay systems here.
    }
};

URHO3D_DEFINE_APPLICATION_MAIN(GameApplication)
)cpp"};
    }
    if (id == "3d")
    {
        return {"3d", "rbfx 3D game starter", "3D, Physics, Navigation, Animation",
            R"cpp(#include <Urho3D/Engine/Engine.h>
#include <Urho3D/Scene/Scene.h>

using namespace Urho3D;

class GameApplication : public Application
{
public:
    explicit GameApplication(Context* context) : Application(context) {}
    void Start() override
    {
        engine_->Create();
        // Create the 3D scene, world partition and gameplay systems here.
    }
};

URHO3D_DEFINE_APPLICATION_MAIN(GameApplication)
)cpp"};
    }
    if (id == "networked")
    {
        return {"networked", "rbfx authoritative multiplayer starter", "3D, Network, Replica, Rollback, DedicatedServer",
            R"cpp(#include <Urho3D/Engine/Engine.h>
#include <Urho3D/Network/Network.h>
#include <Urho3D/Replica/Replica.h>

using namespace Urho3D;

class GameApplication : public Application
{
public:
    explicit GameApplication(Context* context) : Application(context) {}
    void Start() override
    {
        engine_->Create();
        // Configure the server/client role and inject multiplayer gameplay services here.
    }
};

URHO3D_DEFINE_APPLICATION_MAIN(GameApplication)
)cpp"};
    }
    return {};
}

bool WriteText(const fs::path& path, const std::string& text)
{
    std::ofstream output(path, std::ios::binary);
    if (!output)
        return false;
    output << text;
    return static_cast<bool>(output);
}

} // namespace

int main(int argc, char** argv)
{
    if (argc != 4)
    {
        std::cerr << "Usage: ProjectScaffold <2d|3d|networked> <output-directory> <project-name>\n";
        return 2;
    }

    const TemplateSpec spec = FindTemplate(argv[1]);
    if (spec.id.empty())
    {
        std::cerr << "Unknown template: " << argv[1] << "\n";
        return 2;
    }
    const fs::path output = fs::absolute(argv[2]);
    const std::string projectName = argv[3];
    if (projectName.empty())
    {
        std::cerr << "Project name must not be empty.\n";
        return 2;
    }

    std::error_code error;
    fs::create_directories(output / "Source", error);
    if (error)
    {
        std::cerr << "Unable to create output directory: " << error.message() << "\n";
        return 1;
    }

    const std::string cmake = "cmake_minimum_required(VERSION 3.20)\n"
        "project(" + projectName + " LANGUAGES CXX)\n\n"
        "find_package(Urho3D CONFIG REQUIRED)\n"
        "add_executable(" + projectName + " Source/Main.cpp)\n"
        "target_compile_features(" + projectName + " PRIVATE cxx_std_17)\n"
        "target_link_libraries(" + projectName + " PRIVATE Urho3D)\n";
    const std::string projectJson = "{\n"
        "  \"name\": \"" + projectName + "\",\n"
        "  \"template\": \"" + spec.id + "\",\n"
        "  \"features\": [\"" + spec.features + "\"],\n"
        "  \"language\": [\"C++17\", \"Blueprint\", \"rbscript\"],\n"
        "  \"packagingProfile\": \"LinuxDevelopment\"\n"
        "}\n";
    const std::string readme = "# " + projectName + "\n\n" + spec.description + ".\n\n"
        "This project is generated by rbfx-blueprint ProjectScaffold and is designed to use the shared C++, Blueprint and rbscript reflection API.\n\n"
        "## Build\n\n"
        "Configure with `cmake -S . -B build -G Ninja -DCMAKE_PREFIX_PATH=/path/to/rbfx-sdk` and build with `cmake --build build`.\n\n"
        "## Production workflow\n\n"
        "Use the matching `packaging/profiles` profile from the engine repository, run validation tests, and keep generated build products outside source control.\n";

    if (!WriteText(output / "CMakeLists.txt", cmake)
        || !WriteText(output / "project.json", projectJson)
        || !WriteText(output / "README.md", readme)
        || !WriteText(output / "Source" / "Main.cpp", spec.mainSource))
    {
        std::cerr << "Unable to write generated project files.\n";
        return 1;
    }
    std::cout << "Generated " << spec.id << " project at " << output << "\n";
    return 0;
}
