trigger:
  branches:
    include:
      - '*'
    exclude:
      - 'no-ci-*'
      - 'skip-ci-*'

jobs:
  - job: Docs
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - template: cmake.yml
      - bash: |
          sudo apt-get install -y --no-install-recommends doxygen
        displayName: 'Setup'

      - task: CMake@1
        displayName: 'Generate'
        inputs:
          workingDirectory: cmake-build
          cmakeArgs: -DCMAKE_BUILD_TYPE=Release -DURHO3D_ENABLE_ALL=ON -DURHO3D_DOCS=ON -DBUILD_SHARED_LIBS=ON $(Build.SourcesDirectory)

      - task: CMake@1
        displayName: 'Build'
        inputs:
          workingDirectory: cmake-build
          cmakeArgs: --build . --config Release --target doc

      - publish: $(Build.SourcesDirectory)/cmake-build/Docs/html/
        artifact: rbfx-$(Agent.JobName)-$(Build.SourceVersion)
