
if (WIN32)
    get_filename_component(MONO_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Mono;SdkInstallRoot]" ABSOLUTE CACHE)
    if (MONO_PATH)
        set (MONO_FOUND ON)
        set (MONO_INCLUDE_DIRS ${MONO_PATH}/include/mono-2.0)
        set (MONO_LIBRARIES ${MONO_PATH}/lib/mono-2.0-sgen.lib ${MONO_PATH}/lib/MonoPosixHelper.lib)
    endif ()
else ()
    include(FindPkgConfig)
    pkg_check_modules(MONO REQUIRED mono-2)
endif ()
if (NOT MONO_FOUND)
    message (FATAL_ERROR "Mono runtime was not found.")
endif ()
